baseURL = "https://onestla.tech/"
defaultContentLanguage = "fr"
languageCode = "fr-fr"
title = "✊ onestla.tech"
theme = "beautifulhugo"

[Params]
  socialShare = true
  organizationName = "onestla.tech"
  favicon = "avatar.png"
  logo = "header.jpg"
